### ISSUE TITLE
Entropy::random return the desired length

### ISSUE THREAD

**Issue by YiWenTianXia** [blocker-solutions/bip39#2]
when I called
   ` $entropy = Entropy::random(128);`
call multiple times

sometime:
   ` strlen((string)$entropy)`
result is 127

**Comment by hernandev** [comment]
@YiWenTianXia that's because strlen count words, not bits.

for a correct bit count the proper way of doing is:


```php
mb_strlen($entry, '8bit')`
```

This is correct way, both using mb for multibyte strings support, using 8bit per char (UTF-8)
