### ISSUE TITLE
The seed was recovered, but the checksum mismatches.

### ISSUE THREAD

**Issue by ygcool** [blocker-solutions/bip39#4]
`$words = $bip39->setEntropy(new Entropy('2990067947976ee909dd8f9ac5385574257976ea51b9a1acd9546a1d5cdacbe4'))->encode();`
“play absorb junk device sweet spirit oven sick help poem fever patrol furnace universe pink system mammal open federal extend fire remain salad blast”

`$words = $bip39->decode('play absorb junk device sweet spirit oven sick help poem fever patrol furnace universe pink system mammal open federal extend fire remain salad blast');`
**// error：The seed was recovered, but the checksum mismatches.**

How can I solve it?

**Comment by k6xiao** [comment]
After the 12 bit word decode, there is only a 32-bit private key, but the correct eth private key is 64 bits, so it cannot be used.
